apiVersion: apps/v1
kind: Deployment
metadata:
  name: tracking-id-generator
  labels:
    app: tracking-id-generator
spec:
  replicas: 2
  selector:
    matchLabels:
      app: tracking-id-generator
  template:
    metadata:
      labels:
        app: tracking-id-generator
    spec:
      containers:
        - name: tracking-id-generator
          image: tracking-id-generator:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "prod"
            - name: MONGODB_URI
              value: "mongodb://tracking-mongo:27017/tracking-db"
            - name: REDIS_HOST
              value: "tracking-redis"
            - name: KAFKA_BROKER
              value: "tracking-kafka:9092"
          resources:
            limits:
              memory: "512Mi"
              cpu: "500m"
            requests:
              memory: "256Mi"
              cpu: "250m"
---
apiVersion: v1
kind: Service
metadata:
  name: tracking-id-generator
spec:
  type: ClusterIP
  selector:
    app: tracking-id-generator
  ports:
    - port: 8080
      targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tracking-mongo
  labels:
    app: tracking-mongo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tracking-mongo
  template:
    metadata:
      labels:
        app: tracking-mongo
    spec:
      containers:
        - name: mongo
          image: mongo:6.0
          ports:
            - containerPort: 27017
          env:
            - name: MONGO_INITDB_DATABASE
              value: tracking-db
---
apiVersion: v1
kind: Service
metadata:
  name: tracking-mongo
spec:
  type: ClusterIP
  selector:
    app: tracking-mongo
  ports:
    - port: 27017
      targetPort: 27017
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tracking-redis
  labels:
    app: tracking-redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tracking-redis
  template:
    metadata:
      labels:
        app: tracking-redis
    spec:
      containers:
        - name: redis
          image: redis:7.0
          ports:
            - containerPort: 6379
---
apiVersion: v1
kind: Service
metadata:
  name: tracking-redis
spec:
  type: ClusterIP
  selector:
    app: tracking-redis
  ports:
    - port: 6379
      targetPort: 6379
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tracking-kafka
  labels:
    app: tracking-kafka
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tracking-kafka
  template:
    metadata:
      labels:
        app: tracking-kafka
    spec:
      containers:
        - name: kafka
          image: apache/kafka:latest
          ports:
            - containerPort: 9092
          env:
            - name: KAFKA_BROKER_ID
              value: "1"
            - name: KAFKA_LISTENERS
              value: "PLAINTEXT://:9092"
            - name: KAFKA_ZOOKEEPER_CONNECT
              value: "tracking-zookeeper:2181"
---
apiVersion: v1
kind: Service
metadata:
  name: tracking-kafka
spec:
  type: ClusterIP
  selector:
    app: tracking-kafka
  ports:
    - port: 9092
      targetPort: 9092