services:

  kafka:
    image: apache/kafka:latest
    restart: always
    ports:
      - 9092:9092
    networks:
      - kafka-network
    deploy:
      resources:
        limits:
          memory: 350M

networks:
  kafka-network:
    driver: bridge