services:
# redis will write to disk offline
  redis:
    image: redis
    restart: always
    command: redis-server --save 60 1 --loglevel warning
    ports:
      - 6379:6379
    networks:
      - redis-network
    deploy:
      resources:
        limits:
          memory: 128M

networks:
  redis-network:
    driver: bridge